# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 2022 - 2024 Mucse Corporation
#
# Makefile for the Mucse(R) 1GbE PCI Express ethernet driver
#
#

obj-$(CONFIG_MXGBEVF) += rnpgbevf.o
rnpgbevf-objs :=   \
		vf.o \
                mbx.o \
                ethtool.o \
                sysfs.o \
                rnpgbevf_main.o

