# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 2022 - 2024 Mucse Corporation
#
# Makefile for the Mucse(R) 10GbE-2ports PCI Express ethernet driver
#
#

obj-$(CONFIG_MXGBEVF) += rnpvf.o
rnpvf-objs :=   \
		vf.o \
                mbx.o \
                ethtool.o \
                sysfs.o \
                rnpvf_main.o

